name: CI / Lint and Test

on:
  push:
    branches: ['main']
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2.0.2
        with:
          bun-version: 1.2.21

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Lint with ESLint
        run: bunx eslint .

      - name: Prettier format check
        run: bunx --bun prettier --check .

      - name: Typecheck
        run: npx tsc --noEmit

      - name: Test
        run: bun test
