name: Build and Deploy demo to Netlify
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  statuses: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: demo
    env:
      is_live_deploy: ${{ github.ref == 'refs/heads/main' }}
      APP_ENV: demo
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install Netlify CLI
        run: bun install -g netlify-cli

      - name: Deploy to Netlify
        uses: jsmrcaga/action-netlify-deploy@v2.0.0
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_DEPLOY_TO_PROD: ${{ env.is_live_deploy == 'true' }}
          build_directory: dist
          install_command: bun install --frozen-lockfile
          build_command: bun run build
        timeout-minutes: 3

      - name: Run the action
        uses: guibranco/github-status-action-v2@v1.1.13
        with:
          authToken: ${{secrets.GITHUB_TOKEN}}
          context: ${{ env.is_live_deploy == 'true' && 'Netlify live URL' || 'Netlify preview URL' }}
          state: success
          target_url: ${{ env.is_live_deploy == 'true' && env.NETLIFY_LIVE_URL || env.NETLIFY_PREVIEW_URL }}
          sha: ${{github.event.pull_request.head.sha || github.sha}}
