name: Lint

on:
  push:
    branches: ['main']
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Lint with ESLint
        run: bunx eslint .

      - name: Prettier format check
        run: bunx --bun prettier --check .

      - name: Typecheck
        run: npx tsc --noEmit
